name: pluto_menu_bar
description: A menu bar for flutter.
version: 0.1.0
homepage: https://bosskmk.github.io
repository: https://github.com/bosskmk/pluto_menu_bar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
